{"name": "test_login_failed_user_password_wrong[case4]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': 'aaaaaa', 'password': 'aaaaaaaa', 'check': '用户名或密码错误'}"}], "start": 1665209571777, "stop": 1665209572826, "uuid": "5a78ecc3-559d-4920-acf0-7250effea4e3", "historyId": "97beefd09a2753b5b4eebfec0949029b", "testCaseId": "253d57a3ffef1d7866e3686ffe2eb276", "fullName": "TestCases.test_login.TestLogin#test_login_failed_user_password_wrong", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init', 'back_to_login_page')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-E380NSU"}, {"name": "thread", "value": "18584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}